# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 0
  # define b as a counter with the prefix as variable a, and seed as 100.
  minor: $[counter(variables['major'], 10)]

steps:

- bash: echo $(minor)
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install

  displayName: 'npm install and build'
